name: Build HKRPG-Go Commit
on:
  workflow_dispatch:
  repository_dispatch:
    typrs: [hkrpggopull]
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Sync HKRPG-Go
      uses: actions/checkout@v3
      with:
        repository: gucooing/hkrpg-go-public
        ref: "dev"
        path: go/hkrpg
        ssh-key: ${{ secrets.GAYHUB_TOKEN }}
        fetch-depth: 0
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: "1.20"
        check-latest: true

    - name: Go Tidy
      run: cd go/hkrpg && go mod tidy

    - name: Build
      run: cd go/hkrpg && bash build.sh

    - name: Package
      run: |
        zip -r go/hkrpg/build/data.zip go/hkrpg/data/*

    - name: Upload Archive
      uses: actions/upload-artifact@v3
      with:
        name: hkrpg-go
        path: go/hkrpg/build/